### ISSUE TITLE
`PATCH admin/product/{productId}/introduction`에 삭제 백로그 포함

### ISSUE THREAD

**Issue by jinlee0** [Liberty52/product#234]
이거 ~method를 `PUT`으로 바꾸고~ 요청에 이미지가 없을 때 `Product.productIntroductionImageUrl`를 `null`로 하면 '상품소개관리삭제` 기능도 같이 할 거 같은데 어떠신가요?

_Originally posted by @jinlee0 in https://github.com/Liberty52/product/issues/230#issuecomment-1732499615_

**Comment by jinlee0** [comment]
@DryRains 어떠신가요?

**Comment by DryRains** [comment]
일단은 건영님이 아키텍처 관련 이유로 머지는 잠시 대기하라하셔서, 우선 이 PR 머지되면 이후에 수정해보겠습니다! 그 전에 다른 팀원분들이랑 이 건에 대해서 회의시간에 논의해보는것도 좋을거같아요. 피드백 감사합니다😄
